/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ankarauni.folderspace;

import java.io.File;
import java.io.IOException;
import java.nio.file.attribute.BasicFileAttributes;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

/**
 *
 * @author Gorkem
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        initTableFirstTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        folderSelector = new javax.swing.JFileChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        fileTable = new javax.swing.JTable();
        selectFolderButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        staticFolderSizeLabel = new javax.swing.JLabel();
        staticAvailableSpaceLabel = new javax.swing.JLabel();
        staticFileCountLabel = new javax.swing.JLabel();
        folderSizeLabel = new javax.swing.JLabel();
        availableSpaceLabel = new javax.swing.JLabel();
        fileCountLabel = new javax.swing.JLabel();

        folderSelector.setAcceptAllFileFilterUsed(false);
        folderSelector.setApproveButtonToolTipText("");
        folderSelector.setCurrentDirectory(new java.io.File("D:\\Program Library\\incubating-netbeans-11.0-bin\\netbeans\\bin"));
        folderSelector.setDialogTitle("Please select a folder...");
        folderSelector.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FolderSpace");
        setResizable(false);

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        fileTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        fileTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(fileTable);

        selectFolderButton.setText("Select Folder...");
        selectFolderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFolderButtonActionPerformed(evt);
            }
        });

        staticFolderSizeLabel.setText("Folder Size:");

        staticAvailableSpaceLabel.setText("Available Space on Disk:");

        staticFileCountLabel.setText("File Count:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(staticAvailableSpaceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(staticFolderSizeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(staticFileCountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(folderSizeLabel)
                    .addComponent(availableSpaceLabel)
                    .addComponent(fileCountLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staticFolderSizeLabel)
                    .addComponent(folderSizeLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staticAvailableSpaceLabel)
                    .addComponent(availableSpaceLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staticFileCountLabel)
                    .addComponent(fileCountLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectFolderButton, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectFolderButton)
                        .addGap(188, 188, 188)))
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectFolderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFolderButtonActionPerformed
        int returnVal = folderSelector.showOpenDialog(this);
        File[] childFiles;
        
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File selectedFile = folderSelector.getSelectedFile();
            // Safeguard for unintended selection behaviour
            if (selectedFile.isDirectory()) {
                childFiles = selectedFile.listFiles();
                CustomTableModel model = CustomTableModel.createModelFromFiles(childFiles);
                this.registerTableModel(model);
                String folderSize = FileHelper.fileSize(selectedFile.toPath());
                String usableSpaceSize = FileHelper.getUsableSpaceOnDisk(selectedFile);
                folderSizeLabel.setText(folderSize);
                availableSpaceLabel.setText(usableSpaceSize);
                fileCountLabel.setText(childFiles.length + " items");
            }
            
            
        }
    }//GEN-LAST:event_selectFolderButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainForm form = new MainForm();
                form.setVisible(true);
            }
        });
    }
    
    public void initTableFirstTime() {
        fileTable.setRowHeight(25);
        fileTable.setShowGrid(false);
    }
    
    public void initTableAfterChange() {
        int iconColumnIndex = 0;
        int iconColumnWidth = 25;
        TableColumn column = fileTable.getColumnModel()
                .getColumn(iconColumnIndex);
        column.setPreferredWidth(iconColumnWidth);
        column.setMaxWidth(iconColumnWidth);
        column.setMinWidth(iconColumnWidth);
        column.setResizable(false);
    }
    
    // Implicitly considering table model object as immutable.
    // Because once the folder is selected by the user, there is no need to
    // modify the model. Therefore, register the model once when the folder
    // is selected.
    public void registerTableModel(DefaultTableModel model) {
        fileTable.setModel(model);
        // initTableAfterChange() needs to be called after registering models.
        // TODO: Move method call to a custom table event in the future.
        initTableAfterChange();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel availableSpaceLabel;
    private javax.swing.JLabel fileCountLabel;
    private javax.swing.JTable fileTable;
    private javax.swing.JFileChooser folderSelector;
    private javax.swing.JLabel folderSizeLabel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton selectFolderButton;
    private javax.swing.JLabel staticAvailableSpaceLabel;
    private javax.swing.JLabel staticFileCountLabel;
    private javax.swing.JLabel staticFolderSizeLabel;
    // End of variables declaration//GEN-END:variables
}
